### ISSUE TITLE
This code looks very familiar

### ISSUE THREAD

**Issue by nyck33** [amuta/DDPG-MountainCarContinuous-v0#1]
Did you use the Quadcopter project from Udacity Deep Learning as a template?

I was going to do the exact same thing because I graduated from the Deep Learning nanodegree and mountaincarcontinuous is my first openai gym with a continuous action space.  

I just want to know if that's what you did because the code looks similar except you deleted parts related to `task.py` I believe.

**Comment by amuta** [comment]
Sorry for the late reply, and yes, I created this repo from the boilerplate DDPG model provided while I was doing the Udacity's Machine Learning Engineer nanodegree. From what I remember the `MountainCar.py` file should be where is most of my own code. 

I actually didn't expect anyone to ever see this repo, but I will mention the Udacity's project to avoid confusion.
